### ISSUE TITLE
why is needed expand_dims here ? 

### ISSUE THREAD

**Issue by srtianxia** [chenchongthu/NARRE#3]
https://github.com/chenchongthu/NARRE/blob/af17e18f304518ea2870baa52287d48ece4f5890/model/NARRE.py#L38

After embedding，the dimension of the data has become the `[batch_size, number of review , maxlength of review, embedding_dim]` ,but why is needed expand_dims ? 

https://github.com/chenchongthu/NARRE/blob/af17e18f304518ea2870baa52287d48ece4f5890/model/NARRE.py#L56

After expand_dims,there is a reshape ? I don't understand it ,thanks  !

**Comment by chenchongthu** [comment]
Hi,

We rechecked the code, and found that the "expand_dims" operations at line 38 and 46 seem unnecessary (as you have mentioned).

Actually, the two operations have no effect on the execution process and should be removed, because the code then reshaped the user and item embeddings(line 56, line 87).

Thanks!

**Comment by srtianxia** [comment]
@chenchongthu  Hi, Thank you very much！ I find that `uidW` is randomly generated.  but the line 137 uses it，What is `uidW` originally or this parameter is like this, but I don't understand ..  ？ (ID embedding?  I want to know this meaning ！I currently guess that this parameter is trained. )
https://github.com/chenchongthu/NARRE/blob/af17e18f304518ea2870baa52287d48ece4f5890/model/NARRE.py#L30
https://github.com/chenchongthu/NARRE/blob/af17e18f304518ea2870baa52287d48ece4f5890/model/NARRE.py#L137
Thanks again ！

**Comment by chenchongthu** [comment]
Yeah, it's ID embedding. It is added to model the quality of users in a simple way, which helps identify users who always write less-useful reviews.

**Comment by srtianxia** [comment]
> Yeah, it's ID embedding. It is added to model the quality of users in a simple way, which helps identify users who always write less-useful reviews.

Very thankful.
