### ISSUE TITLE
Can you share your paper "Social Aentional Memory Network: Modeling Aspect- and Friend-level Dierences in Recommendation" code with us

### ISSUE THREAD

**Issue by sshzhang** [chenchongthu/NARRE#4]
Hello chenchong:
   Recently, I read you paper "Social Aentional Memory Network: Modeling Aspect- and
Friend-level Dierences in Recommendation",   I also want to major in social reacommendation . so if possible , I hope you can share you code with us. Thank you very much!

**Comment by chenchongthu** [comment]
The code will be published soon.
