### ISSUE TITLE
请问可以提供NARRE可解释性部分的源代码吗？

### ISSUE THREAD

**Issue by MooreAndMoore** [chenchongthu/NARRE#9]
如题所示，我们在学习您的论文时，对可解释性部分的理解还不是太深刻，请问可以提供一下吗？

**Comment by daixing1** [comment]
同问，有的话能发一份么

**Comment by daixing1** [comment]
前面那兄弟，我训练代码用GoogleNews-vectors-negative300.bin加载一直内存溢出，知道怎么解决这个问题么，已经搞一星期了还没搞定，求教

**Comment by MooreAndMoore** [comment]
可能是内存太小了吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: daixing1 <notifications@github.com&gt;
发送时间: 2019年10月31日 15:14
收件人: chenchongthu/NARRE <NARRE@noreply.github.com&gt;
抄送: MooreAndMoore <573460349@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[chenchongthu/NARRE] 请问可以提供NARRE可解释性部分的源代码吗？ (#9)




前面那兄弟，我训练代码用GoogleNews-vectors-negative300.bin加载一直内存溢出，知道怎么解决这个问题么，已经搞一星期了还没搞定，求教

**Comment by chenchongthu** [comment]
抱歉由于我们之前是在云服务器上做的这部分实验，之后云到期之后线上标注的数据有一些遗失（当时我还是一个新人没有及时备份数据的意识...），所以很遗憾这部分的统计相关代码没有上传。

在可解释部分里，我们首先是通过attention score值对review进行了排序，然后跟现在存在的一些review排序方式（Latest，Length, Top_Rated_Useful）进行了一下比较，并通过线上标注平台收集了大家对评论有用性的标注，之后通过统计来展示我们方法对于提供“评论级别的解释”的有用性。

**Comment by MooreAndMoore** [comment]
我们在自己做的时候，大致地仿照了您的思路。但是在数据预处理方面，我还有一些疑问，不知道您可不可以帮忙解答一下：在数据预处理部分，您说对于每个数据集，只保留了至少存在一个rated review的那些items。那请问对于您为了维持固定长度而pad为0的那些review，是否也要进行attention_score,latest,length的排序工作？如果是的话，那么时间和长度应该分别赋值为什么呢？十分感谢！！

**Comment by chenchongthu** [comment]
对于pad为0的空白review,是直接排在列表的后面的，或者说我们只对真实的review进行了这几种方法的排序，对于补齐的空白review没有排序

**Comment by MooreAndMoore** [comment]
thx!

**Comment by luoxintao** [comment]
请问，在论文中提及到的UID嵌入，是通过什么方式嵌入的呢？我在文章中没有看到关于UID的一些处理。比如，以何种方式嵌入，嵌入维度等等。其次是在运行作者代码时，LFM的那部分是不是没有添加进去？刚刚入坑推荐系统的新生，望不吝赐教，感谢。

**Comment by MooreAndMoore** [comment]
> 请问，在论文中提及到的UID嵌入，是通过什么方式嵌入的呢？我在文章中没有看到关于UID的一些处理。比如，以何种方式嵌入，嵌入维度等等。其次是在运行作者代码时，LFM的那部分是不是没有添加进去？刚刚入坑推荐系统的新生，望不吝赐教，感谢。

（1）你去好好看看代码，在NARRE.py里面在attention计算的那部分有相关代码。
（2）LFM他是拆成了好几个零散的部分一点一点地加起来的，在最后的prediction预测那里，你好好推导一遍才能看懂他写的意思。

**Comment by luoxintao** [comment]
感谢您的回复！
